name: EOTorchLoader
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip
  - numpy>=1.19
  - matplotlib>=3.1.3
  - pytorch>=1.10.0
  - tqdm>=4.40.0
  - rasterio>=1.1.5
  - pandas>=1.0.0
  - pytorch-lightning>=1.5.8
