# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import sys
import os
from os.path import abspath, dirname
from sphinx.domains import Domain
from typing import Dict, List, Tuple
from unittest import mock
from unittest.mock import MagicMock


# -- Project information -----------------------------------------------------

project = "EOTorchLoader"
copyright = "2022, Nicolas DAVID"
author = "Nicolas DAVID"

module_path = os.path.join(abspath(dirname(dirname(dirname(__file__)))), "src")
print(module_path)
sys.path.insert(0, module_path)

# The full version, including alpha/beta/rc tags
release = "0.1"

# -- mock dependencies for generation on githb pages etc..

# fmt: off
try:
    import torch  # noqa
except ImportError:
    for m in [
        "torch", "torchvision", "torch.nn", "torch.nn.parallel", "torch.distributed", "torch.multiprocessing", "torch.autograd",
        "torch.autograd.function", "torch.nn.modules", "torch.nn.modules.utils", "torch.utils", "torch.utils.data", "torch.onnx",
        "torchvision", "torchvision.ops",
    ]:
        sys.modules[m] = mock.Mock(name=m)
    sys.modules['torch'].__version__ = "1.7"  # fake version
    HAS_TORCH = False
else:
    HAS_TORCH = True

autodoc_mock_imports = []
for m in [
    "rasterio", "numpy", "pytorch_lightning", "pandas",
    "matplotlib.pyplot"
]:
    autodoc_mock_imports.append(m)
    #sys.modules[m] = mock.Mock(name=m)

for m in [
    "rasterio.windows"
]:
    sys.modules[m] = mock.MagicMock()
# fmt: on


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autosummary",
    "sphinx.ext.autodoc",
    "sphinx.ext.extlinks",
    "sphinx.ext.todo",
    "sphinx.ext.githubpages",
    "sphinx.ext.mathjax",
    "sphinx.ext.ifconfig",
    "sphinx.ext.napoleon",
    "nbsphinx",
    "sphinx_panels",
    "sphinx_tabs.tabs",
    "numpydoc"
]

# generate autosummary pages
autosummary_generate = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["**.ipynb_checkpoints"]

# sphinx-panels shouldn't add bootstrap css since the pydata-sphinx-theme
# already loads it
panels_add_bootstrap_css = False

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = "en"

add_module_names = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# A list of prefixs that are ignored when creating the module index. (new in Sphinx 0.6)
modindex_common_prefix = ["eotorchloader."]

doctest_global_setup = "import eotorchloader as eotl"

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "pydata_sphinx_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

html_css_files = [
    "css/getting_started.css",
    "css/eotorch.css",
]

html_theme_options = {
    "external_links": [],
    "github_url": "https://github.com/ndavid/EOTorchLoader",
}


numpydoc_show_class_members = False
